# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - main: main.go
    binary: gotail
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X github.com/borisdvlpr/gotail/cmd.version={{.Version}}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

nfpms:
  - package_name: gotail
    homepage: https://github.com/borisdvlpr/gotail
    maintainer: Eduardo Miranda <eduffmiranda@hotmail.com>
    license: BSD-3-Clause
    description: |-
      Bootstrap Tailscale into your Raspberry Pi and join it to your tailnet automatically from the very first boot.
    formats:
      - apk
      - deb
      - rpm
      - archlinux

brews:
  - repository:
      owner: borisdvlpr
      name: homebrew-gotail
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/borisdvlpr/gotail
    description: "Bootstrap Tailscale into your Raspberry Pi from the very first boot."
    license: BSD-3-Clause
    test: |
      system "#{bin}/gotail --version"
    install: |
      bin.install "gotail"

winget:
  - name: gotail
    package_identifier: borisdvlpr.gotail
    publisher: borisdvlpr
    license: BSD-3-Clause
    copyright: "Eduardo Miranda"
    homepage: https://github.com/borisdvlpr/gotail
    short_description: "Bootstrap Tailscale into your Raspberry Pi from the very first boot."
    description: |-
      Bootstrap Tailscale into your Raspberry Pi and join it to your
      tailnet automatically from the very first boot.
    publisher_url: https://github.com/borisdvlpr
    publisher_support_url: https://github.com/borisdvlpr/gotail/issues
    repository:
      owner: borisdvlpr
      name: winget-pkgs
      branch: "gotail-{{.Version}}"
      token: "{{ .Env.WINGET_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

changelog:
  sort: asc
  filters:
    exclude:
      - "^ci"
      - "^chore"
      - "^docs"
      - "^refactor"
      - "^style"
      - "^test"
